- name: remove hosts file
  file:
    path: /etc/ansible/hosts.d/custom
    state: absent

- name: link ansible hosts file
  file:
    src: /vagrant/inventory.ini
    dest: /etc/ansible/hosts.d/custom
    state: link

- name: copy ssh config
  file:
    src: /vagrant/ssh-config
    dest: /home/vagrant/.ssh/config.d/local.conf
    state: link

